#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --partition LYRA1
#SBATCH --time=96:00:00
#SBATCH --mem=256000mb
#
#SBATCH --job-name=API-MASTER
#
#SBATCH --mail-type=failed,end
#SBATCH --mail-user=p_esch01@uni-muenster.de
#SBATCH --output output.slurm
#SBATCH --no-requeue
#
############## Preparing the Task ############
# create local scratch directory
LOCALTMP=/scratch/p_esch01/$SLURM_JOB_ID
BACKDIR=$SLURM_SUBMIT_DIR
cd $BACKDIR
if [ ! -e $LOCALTMP ]
then
mkdir -p $LOCALTMP
fi
rsync -avu * $LOCALTMP/
echo $HOSTNAME:$LOCALTMP > LOCALDIR
cd $LOCALTMP
############## Running the Task ############
export DATABASE_DIR="/WORK/p_esch01/scratch_calc"
source /WORK/p_esch01/progs/serenity_intel/serenity.sh
python /WORK/p_esch01/progs/restApi/src/pFaTAsync.py > out-MASTER
############## Ending the Task ############
cd $BACKDIR
rsync -avu $LOCALTMP/* $BACKDIR/ && rm -rf $LOCALTMP && echo "$LOCALTMP deleted" >>LOCALDIR
