sending incremental file list
APICommunicator.py
DockerSDK.py
JsonHelper.py
LOCALDIR
PrepareSLURM.py
akcluster.py
error_YSS26NWT66
launcher_YSS26NWT66.out
output.slurm
pFaTAsync.py
sFaTAsync.py
sbatch_script_swarmYSS26NWT66
sbatch_script_swarmZJQTSIDJ4R
__pycache__/
__pycache__/APICommunicator.cpython-38.pyc
__pycache__/JsonHelper.cpython-38.pyc
__pycache__/akcluster.cpython-38.pyc

sent 39,137 bytes  received 332 bytes  78,938.00 bytes/sec
total size is 37,705  speedup is 0.96
